export default function useDummyData() {
  const events = [
    {
      id: 1,
      title: "Sumbu Filosofi",
      date: "23 AGUSTUS 2025",
      month: "23 AUG 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Tugu Yogyakarta",
      distance: "2 km",
      image:
        "https://akcdn.detik.net.id/community/media/visual/2021/12/12/international-ethnic-music-festival-2021.jpeg?w=700&q=90",
      description: "Kehidupan manusia dalam keseimbangan lahir–batin",
      capacity: "200",
      attendees: 145,
      organizer: "Ruang Teater",
      category: "Teater Budaya Kontemporer",
      price: "Rp 100.000",
    },
    {
      id: 2,
      title: "Sendra Tari",
      date: "23 AGUSTUS 2025",
      month: "23 AUG 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Prambanan",
      distance: "15 km",
      image:
        "https://airport.id/wp-content/uploads/2017/03/ramayana-2.jpg",
      description: "Pertunjukan sendra tari tradisional Jawa.",
      capacity: "300",
      attendees: 220,
      organizer: "Budaya Nusantara",
      category: "Traditional Dance",
      price: "Rp 75.000",
    },
    {
      id: 3,
      title: "Wayang",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "TBY",
      distance: "5 km",
      image:
        "https://salutbali.com/wp-content/uploads/2024/03/Wayang-Kulit-dalam-Konteks-Modern.webp",
      description: "Drama tari Wayang Wong penuh makna budaya.",
      capacity: "150",
      attendees: 90,
      organizer: "Sanggar Seni",
      category: "Traditional Art",
      price: "Rp 50.000",
    },
    {
      id: 4,
      title: "Kethoprak",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Kotagede",
      distance: "3 km",
      image:
        "https://warta.jogjakota.go.id/assets/instansi/warta/article/20220713104357.JPG",
      description: "Pertunjukan kethoprak klasik penuh cerita rakyat.",
      capacity: "180",
      attendees: 120,
      organizer: "Teater Rakyat",
      category: "Drama",
      price: "Rp 60.000",
    },
    {
      id: 5,
      title: "Loro Blonyo",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Taman Budaya Yogyakarta",
      distance: "12 km",
      image:
        "https://akcdn.detik.net.id/visual/2023/03/05/drama-musikal-the-great-rahwana-2_169.jpeg?w=1200",
      description: "Harmoni gamelan Jawa dalam konser spesial.",
      capacity: "250",
      attendees: 200,
      organizer: "Komunitas Teater",
      category: "Teater Budaya",
      price: "Rp 80.000",
    },
    {
      id: 6,
      title: "Ruang Tunggu Nomor 3",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Taman Budaya",
      distance: "8 km",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMDncb5RWotGmjnFogDaSQxF-hUwDlEEyr8w&s",
      description: "Orang-orang menunggu panggilan yang tak kunjung datang.",
      capacity: "220",
      attendees: 180,
      organizer: "Teater Modern",
      category: "Teater Psikologis",
      price: "Rp 90.000",
    },
    {
      id: 7,
      title: "404: Not Found",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Kampus UAD 4",
      distance: "100 m",
      image:
        "https://i0.wp.com/tambahpinter.com/wp-content/uploads/2020/04/MODERN-548x365.jpg",
      description: "Manusia hidup dalam sistem digital yang menghapus eksistensi..",
      capacity: "160",
      attendees: 140,
      organizer: "Teater modern",
      category: "Teater Kontemporer",
      price: "Rp 120.000",
    },
    {
      id: 8,
      title: "Mute",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Alun-Alun",
      distance: "6 km",
      image:
        "https://worldoftheatreandart.com/wp-content/uploads/2014/06/modern-tehatre-2.jpg",
      description: "FKarakter bisa berbicara, tapi tidak pernah benar-benar didengar..",
      capacity: "400",
      attendees: 350,
      organizer: "Cultural Fest",
      category: "Teater Psikologis",
      price: "Rp 70.000",
    },
    {
      id: 9,
      title: "Tiga Kursi Kosong",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Balai Kota",
      distance: "7 km",
      image:
        "https://barta1.com/wp-content/uploads/2021/03/teater-sangihe.jpg",
      description: "Tiga kursi kosong mewakili orang yang tak hadir.",
      capacity: "300",
      attendees: 280,
      organizer: "Drama Circle",
      category: "Drama Modern",
      price: "Rp 150.000",
    },
    {
      id: 10,
      title: "Konten atau Mati",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "auditorium UNY",
      distance: "9 km",
      image:
        "https://www.riauonline.co.id/foto/bank/images2/Karya-tari-kontemporer.jpg",
      description: "Hidup harus selalu layak di-upload.",
      capacity: "200",
      attendees: 160,
      organizer: "Theater Group",
      category: "Teater Kritik Sosial",
      price: "Rp 110.000",
    },
    {
      id: 11,
      title: "Gending yang Terlupa",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Studio Gendhing Bahana",
      distance: "10 km",
      image:
        "https://uad.ac.id/wp-content/uploads/images/Panggung-Gamelan-Gending-Bahana-UAD.jpg",
      description: "Seorang penabuh gamelan muda berjuang mempertahankan kelompoknya.",
      capacity: "250",
      attendees: 230,
      organizer: "komunitas Gamelan",
      category: "Seni Karawitan",
      price: "Rp 130.000",
    },
    {
      id: 12,
      title: "Sekar Jagad",
      date: "23 AGUSTUS 2025",
      month: "23 AGT 2025",
      time: "8:30 pm - 11:00 pm",
      location: "Taman Budaya",
      distance: "20 km",
      image:
        "https://akcdn.detik.net.id/community/media/visual/2023/03/05/drama-musikal-the-great-rahwana-6_169.jpeg?w=620",
      description: "Sekar Jagad menggambarkan keindahan keberagaman yang berpadu menjadi satu kesatuan harmoni melalui simbol batik dan bahasa visual panggung.",
      capacity: "500",
      attendees: 450,
      organizer: "tradisional Arts",
      category: "Seni Rupa Tradisional",
      price: "Rp 200.000",
    }
  ];

  return { events };
}